application:
  subdomain: ting-reader
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://ting-reader:3000/
services:
  ting-reader:
    # dqsq2e2/ting-reader:1.0.2
    # upstream: dqsq2e2/ting-reader:1.5.3
    image: registry.lazycat.cloud/czyt/dqsq2e2/ting-reader:b994cfbfdb72a79e
    environment:
      - RUST_LOG=info
      - TING_SERVER__HOST=0.0.0.0
      - TING_SERVER__PORT=3000
      - TING_SECURITY__JWT_SECRET={{ stable_secret "ting$reader"}}
      - TEMP_DIR=/app/temp
      - DATA_DIR=/app/data
      - STORAGE_DIR=/app/storage
    binds:
      - /lzcapp/var/data:/app/data
      - /lzcapp/var/storage:/app/storage
      - /lzcapp/var/plugins:/app/plugins
      - /lzcapp/cache/temp:/app/temp
    cpu_shares: 512
    mem_limit: 512M
