package: community.lazycat.app.ting-reader
version: 1.0.2
name: Ting Reader
description: "A modern web-based e-book reader application"
min_os_version: 1.5.0
license: MIT
homepage: https://github.com/dqsq2e2/ting-reader
author: dqsq2e2

locales:
  en:
    name: "Ting Reader"
    description: "A lightweight, self-hosted audiobook platform that supports automatic metadata scraping and multi-device playback progress synchronization"
  zh:
    name: "Ting Reader"
    description: "一个轻量级的自托管有声书平台，支持自动刮削元数据、多端播放进度同步"
